image: docker:20.10.16

services:
  - name: docker:20.10.16-dind
    command: ["--insecure-registry=gitlab.cn-kimototy.example.com:5050"]

stages:
  - build
  - test
  - deploy

variables:
  GIT_SSL_NO_VERIFY: "true"
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH

before_script:
  # Loging to repository
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

  # Install ca.crt
  - ls /etc/gitlab-runner/certs/ca.crt
  - cp /etc/gitlab-runner/certs/ca.crt /usr/local/share/ca-certificates/
  - ls /usr/local/share/ca-certificates/
  - cat /etc/gitlab-runner/certs/ca.crt >> /usr/local/share/ca-certificates/ca-certificates.crt
  - update-ca-certificates

  # Install kubectl
  - wget "https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl"
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl

  # Install knative func
  - wget https://github.com/knative/func/releases/download/knative-v1.9.0/func_linux_amd64
  - mv func_linux_amd64 kn-func
  - chmod +x kn-func
  - mv kn-func /usr/local/bin
  - kn-func version

build:
  stage: build
  script:
    # Build application, create container image and push to container registry
    - kn-func build --registry $CONTAINER_IMAGE --push -v

# test:
#   stage: test
#   script:
#     - Some test commands ...

deploy:
  script:
    # Get context and set context to kubernetes agent
    - kubectl config get-contexts
    - kubectl config use-context tk.automate/cmcustdb-backend:cn-kimototy

    # Deploy application to kubernetes
    - kn-func deploy --build=false --push=false --image $CONTAINER_IMAGE/$CI_PROJECT_NAME:latest --namespace prod -v
  only:
    - main
